version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inss_development
      REDIS_URL: redis://redis:6379/0

    depends_on:
      postgres:
        condition: service_healthy
    command: ["rails", "server", "-b", "0.0.0.0"]

  postgres:
    image: postgres:17.2
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inss_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inss_development"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  jobs:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
      - postgres
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inss_development
      REDIS_URL: redis://redis:6379/0

volumes:
  postgres_data:
  bundle_cache:
