version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
