version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inss_development
    depends_on:
      postgres:
        condition: service_healthy
    command: ["rails", "server", "-b", "0.0.0.0"]

  postgres:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inss_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inss_development"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
